try{

  let a ;
  console.log(a.length);
  console.log("hi there");

}catch(e){
  console.log("inside catch statement");
}

console.log("end");

